// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxManager.Infra.Data;

namespace TaxManager.Infra.Data.Migrations
{
    [DbContext(typeof(TaxManagerContext))]
    partial class TaxManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TaxManager.Core.Entities.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("DailyTaxRate")
                        .HasColumnType("float");

                    b.Property<double>("MonthlyTaxRate")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("WeeklyTaxRate")
                        .HasColumnType("float");

                    b.Property<double>("YearlyTaxRate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Municipalities");
                });
#pragma warning restore 612, 618
        }
    }
}
